[package]
name = "brainfuck-interpreter"
version = "1.0.0"
edition = "2021"
authors = ["stouma915"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
phf = { version = "0.10.1", features = ["macros"] }